DROP FUNCTION IF EXISTS FIBONACCI;
DELIMITER //

CREATE FUNCTION FIBONACCI (num INT)
RETURNS INT DETERMINISTIC
BEGIN
	DECLARE fib0 INT DEFAULT 0;
	DECLARE fib1 INT DEFAULT 1;
	DECLARE fib INT;
	DECLARE i INT DEFAULT 1;
	
	IF num = 0 THEN
		RETURN fib0;
	END IF;
	IF num = 1 THEN
		RETURN fib1;
	END IF;
	
	WHILE i < num DO
		SET i = i + 1;
    SET fib = fib0 + fib1;
    SET fib0 = fib1;
    SET fib1 = fib;
  END WHILE;
    RETURN fib;
END//

SELECT FIBONACCI(10)
